#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Dartboard.Resource", IsApplication=true)]

namespace Dartboard
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050001
			public const int legsArray = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int startScoreArray = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int background = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int lightBlue = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int red = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int white = 2131099649;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dartboard = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dartboardoverlay = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000b
			public const int Checkout = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int Checkout2 = 2131230733;
			
			// aapt resource value: 0x7f080007
			public const int Main = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int addPlayer = 2131230721;
			
			// aapt resource value: 0x7f08000a
			public const int dart1 = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int dart2 = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int dartboard = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int dartboardoverlay = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int legsSpinner = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int numLegs = 2131230724;
			
			// aapt resource value: 0x7f08000f
			public const int playerName = 2131230735;
			
			// aapt resource value: 0x7f080000
			public const int playerNames = 2131230720;
			
			// aapt resource value: 0x7f080006
			public const int startGame = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int startScoreBanner = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int startScoreSpinner = 2131230723;
			
			// aapt resource value: 0x7f08000e
			public const int undo = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateGame = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int NamePlayer = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int legsPrompt = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int playerNameHint = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int scorePrompt = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int DartsAppStyle = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int buttonStyle = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
